server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/your_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

kb:
  storage:
    base-dir: ./data/kb   # 文档落盘根目录
  worker:
    base-url: http://localhost:8000  # FastAPI
